version: "3.9"

services:
  job-web:
    build: .
    container_name: job-web
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=postgresql://jobbot:JoBB0t@db:5432/jobbot
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nginx-proxy-net
      - internal_network
    command: gunicorn jobsearchbot.wsgi:application --bind 0.0.0.0:8010 --workers 2 --timeout 120


  job-bot:
    build: .
    container_name: job-bot
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=postgresql://jobbot:JoBB0t@db:5432/jobbot
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal_network
    command: python manage.py run_bot

  db:
    image: postgres:15
    container_name: jobbot-db
    environment:
      POSTGRES_USER: jobbot
      POSTGRES_PASSWORD: JoBB0t
      POSTGRES_DB: jobbot
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network


volumes:
  db_data:

networks:
  internal_network:
    driver: bridge
  nginx-proxy-net:
    external: true
