services:
  
  job-web:
    build: .
    container_name: job-web
    volumes:
      - .:/app
    env_file:
      - .env
    command: gunicorn jobsearchbot.wsgi:application --bind 0.0.0.0:8010 --workers 2 --timeout 120
    depends_on:
      - db
      - redis
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_HOST=db
      - POSTGRES_DB=jobbot
      - POSTGRES_USER=jobbot
      - POSTGRES_PASSWORD=JoBB0t
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - nginx-proxy-net
      - internal_network


  job-bot:
    build: .
    container_name: job-bot
    volumes:
      - .:/app
    env_file:
      - .env
    command: python manage.py run_bot
    depends_on:
      - db
      - redis
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_HOST=db
      - POSTGRES_DB=jobbot
      - POSTGRES_USER=jobbot
      - POSTGRES_PASSWORD=JoBB0t
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - internal_network

  db:
    image: postgres:15
    container_name: jobbot-db
    environment:
      POSTGRES_USER: jobbot
      POSTGRES_PASSWORD: JoBB0t
      POSTGRES_DB: jobbot
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network

  redis:
    image: redis:alpine
    container_name: jobbot-redis
    networks:
      - internal_network
    restart: unless-stopped

  celery:
    build: .
    container_name: jobbot-celery
    command: celery -A jobsearchbot worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=jobbot
      - POSTGRES_USER=jobbot
      - POSTGRES_PASSWORD=JoBB0t
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - internal_network
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: jobbot-celery-beat
    command: celery -A jobsearchbot beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=jobbot
      - POSTGRES_USER=jobbot
      - POSTGRES_PASSWORD=JoBB0t
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - internal_network
    restart: unless-stopped


volumes:
  db_data:

networks:
  internal_network:
    driver: bridge
  nginx-proxy-net:
    external: true
