# Generated by Django 5.2.3 on 2025-06-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('can_set_alert', models.BooleanField(default=False)),
                ('can_build_cv', models.BooleanField(default=True)),
                ('can_view_all_jobs', models.BooleanField(default=False)),
                ('can_save_jobs', models.BooleanField(default=True)),
                ('can_receive_alerts', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.subscriptiontier'),
        ),
    ]
