# Generated by Django 5.2.3 on 2025-06-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_jobboard_subscriptiontier_user_subscription_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
    ]
