# Generated by Django 5.2.3 on 2025-07-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_user_subscription_tier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobBoard',
        ),
    ]
