# Generated by Django 5.2.3 on 2025-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_delete_jobboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_title', models.CharField(max_length=255, unique=True)),
                ('normalized_title', models.SlugField(max_length=255, unique=True)),
                ('result_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
