# Generated by Django 5.2.4 on 2025-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_interviewsession_interviewresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
