# Generated by Django 5.2.8 on 2025-11-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_interviewresponse_is_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Platform User', 'verbose_name_plural': 'Platform Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='link_code',
            field=models.CharField(blank=True, help_text='Code to link account', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='link_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('subscription_status', models.CharField(default='Free', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('search_count', models.IntegerField(default=0)),
                ('cv_data', models.JSONField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.tenant')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'unique_together': {('tenant', 'user_id')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_user',
            field=models.ForeignKey(blank=True, help_text='Link to unified tenant user profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_accounts', to='bot.tenantuser'),
        ),
    ]
