# Generated by Django 5.2.8 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_tenant_alter_user_options_user_link_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20, null=True),
        ),
    ]
